- name: variables to print
  hosts: web
  vars:
    COURSE: "Devops with AWS from PLAY level"
    DURATION: "120HRS"
    TRAINER: "sivakumar Reddy M"
  vars_files:
  - name: COURSE
    prompt: please enter the course name
    private: false # not confidential
  tasks:
  - name: print the information
    vars:
      #COURSE: "Devops with AWS from TASK level"
      DURATION: "120HRS"
      TRAINER: "sivakumar Reddy M"
    ansible.builtin.debug:
      msg: "Hi,I am learning {{ COURSE }}"

#1.command line/args
#2.Task level
#3.files
#4.prompt