- name: create user
  hosts:
  become: yes
  tasks:
  - name: check user exist or not
    ansible.builtin.command: id expense
    Register: USER #here USER is variable that gets output from above command

  - name: print the user information
    ansible.builtin.debug:
      msg: "user info: {{ USER }}"
